SKIPUNZIP=1

# Extract module files
unzip -qjo "$ZIPFILE" -x 'META-INF/*' 'customize.sh' -d "$MODPATH" >&2

ui_print ""
ui_print "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
ui_print "   DoseBreaker"
ui_print "   by Vetheon @ Lyrinox Technologies"
ui_print "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
ui_print ""

# -----------------------------
# Root Manager Detection
# -----------------------------
if [ -n "$APATCH_VER" ]; then
    ROOT_MGR="APatch"
elif [ -n "$KSU_VER" ]; then
    ROOT_MGR="KernelSU"
elif [ -n "$MAGISK_VER" ]; then
    ROOT_MGR="Magisk"
else
    ROOT_MGR="Unknown"
fi

# -----------------------------
# Package Listing Helper
# -----------------------------
list_pkgs() {
    if command -v pm >/dev/null 2>&1; then
        pm list packages 2>/dev/null
    else
        cmd package list packages 2>/dev/null
    fi
}

# -----------------------------
# Detect Audio HAL (robust)
# -----------------------------
ui_print "  Detecting audio HAL..."

IS_AIDL=false
IS_HIDL=false

if getprop | grep -q "audio-hal-aidl"; then
    IS_AIDL=true
    ui_print "  Audio HAL: AIDL"
elif getprop | grep -q "vendor.audio-hal"; then
    IS_HIDL=true
    ui_print "  Audio HAL: HIDL (vendor)"
elif getprop | grep -q "audio-hal"; then
    IS_HIDL=true
    ui_print "  Audio HAL: HIDL (generic)"
else
    ui_print "  Audio HAL: Unknown"
fi

# -----------------------------
# Detect PSD Resampler Support
# -----------------------------
HAS_PSD=false

if getprop | grep -q "ro.audio.resampler.psd"; then
    HAS_PSD=true
    ui_print "  PSD resampler detected"
else
    ui_print "  No PSD resampler support"
fi

# -----------------------------
# Detect Audio Mods
# -----------------------------
ui_print ""
ui_print "  Detecting audio mods..."

HAS_JAMESDSP=false
HAS_V4A=false

for PKG in james.dsp me.timschneeberger.rootlessjamesdsp james.dsp.manager; do
    if list_pkgs | grep -q "$PKG"; then
        HAS_JAMESDSP=true
        ui_print "  ✓ JamesDSP detected ($PKG)"
        break
    fi
done

for PKG in com.pittvandewitt.viperfx com.vipercn.viper4android_v2 com.vipercn.viper4android; do
    if list_pkgs | grep -q "$PKG"; then
        HAS_V4A=true
        ui_print "  ✓ ViPER4Android detected ($PKG)"
        break
    fi
done

if [ "$HAS_JAMESDSP" = false ] && [ "$HAS_V4A" = false ]; then
    ui_print "  No audio mods detected"
fi

# -----------------------------
# Prepare Prop Script
# -----------------------------
PROP_FILE="$MODPATH/audio_props.sh"

cat << 'EOF' > "$PROP_FILE"
#!/system/bin/sh
# Auto-generated by installer - do not edit manually
EOF

chmod 0755 "$PROP_FILE"

write_prop() {
    echo "setprop $1 $2" >> "$PROP_FILE"
    ui_print "  ✓ $1 = $2"
}

# -----------------------------
# Base Audio Tweaks (SAFE)
# -----------------------------
ui_print ""
ui_print "  Applying base audio tweaks..."

write_prop "audio.offload.disable" "false"
write_prop "audio.offload.min.duration.secs" "15"
write_prop "audio.offload.gapless.enabled" "true"

# Deep buffer for sustained playback quality
write_prop "audio.deep_buffer.media" "true"

# -----------------------------
# Safe Volume Props (best effort)
# -----------------------------
ui_print ""
ui_print "  Applying safe volume props..."

write_prop "audio.safemedia.bypass" "true"
write_prop "audio.safemedia.force" "false"
write_prop "ro.config.media_vol_steps" "30"

# -----------------------------
# HAL-Specific Tweaks
# -----------------------------
if [ "$IS_HIDL" = true ]; then
    ui_print ""
    ui_print "  Applying HIDL tweaks..."

    write_prop "persist.audio.hifi" "true"
    write_prop "persist.audio.fluence.voicecall" "none"
    write_prop "persist.audio.fluence.speaker" "none"
fi

# -----------------------------
# Audio Mod Optimizations
# -----------------------------
if [ "$HAS_JAMESDSP" = true ] || [ "$HAS_V4A" = true ]; then
    ui_print ""
    ui_print "  Applying audio mod optimizations..."

    write_prop "audio.effects.skiptranscode" "true"
    write_prop "af.fast_track_multiplier" "1"
fi

# -----------------------------
# Resampler Strategy (SAFE)
# -----------------------------
ui_print ""
ui_print "  Configuring resampler..."

if [ "$HAS_PSD" = true ]; then
    ui_print "  Using dynamic high-quality resampler (safe mode)"

    write_prop "af.resampler.quality" "7"

    # NOTE: PSD tuning is applied at runtime in service.sh
    # to avoid install-time incompatibility
else
    ui_print "  Using safe resampler (quality=4)"

    write_prop "af.resampler.quality" "4"
fi

# -----------------------------
# Finish
# -----------------------------
ui_print ""
ui_print "  Root manager: $ROOT_MGR"
ui_print ""
ui_print "  ✓ Installation complete"
ui_print "  ✓ Runtime enforcement enabled"
ui_print ""
ui_print "  ⚠ Reboot required!"
ui_print ""
ui_print "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
ui_print ""
ui_print "  If this module helped you,"
ui_print "  consider sponsoring us on GitHub!"
ui_print ""
ui_print "  github.com/sponsors/LyrinoxTechnologies"
ui_print ""
ui_print "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
ui_print ""
