SKIPUNZIP=1
unzip -qjo "$ZIPFILE" -x 'META-INF' 'customize.sh' -d $MODPATH >&2

ui_print ""
ui_print "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
ui_print "   Disable Safe Media Volume"
ui_print "   by Vetheon @ Lyrinox Technologies"
ui_print "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
ui_print ""

# Detect root manager
if [ -n "$APATCH_VER" ]; then
    ROOT_MGR="APatch"
elif [ -n "$KSU_VER" ]; then
    ROOT_MGR="KernelSU"
elif [ -n "$MAGISK_VER" ]; then
    ROOT_MGR="Magisk"
else
    ROOT_MGR="Unknown"
fi

# Write props to a config file for service.sh to apply after reboot
PROP_FILE="$MODPATH/audio_props.sh"
echo "#!/system/bin/sh" > "$PROP_FILE"
echo "# Auto-generated by installer - do not edit manually" >> "$PROP_FILE"

write_prop() {
    local PROP=$1
    local VALUE=$2
    local CURRENT
    CURRENT=$(getprop "$PROP" 2>/dev/null)
    if [ -n "$CURRENT" ]; then
        echo "setprop $PROP $VALUE" >> "$PROP_FILE"
        ui_print "  ✓ $PROP = $VALUE"
    fi
}

ui_print "  Detecting audio HAL type..."

IS_AIDL=false
IS_HIDL=false

# -- HAL Type detection --
if getprop init.svc.vendor.audio-hal-aidl > /dev/null 2>&1 && \
    [ -n "$(getprop init.svc.vendor.audio-hal-aidl)" ]; then
        IS_AIDL=true
        ui_print "  Audio HAL: AIDL"
fi

# HIDL HAL registers as vendor.audio-hal-2.0 or similar
if getprop init.svc.vendor.audio-hal-2-0 > /dev/null 2>&1 && \
    [ -n "${getprop init.svc.vendor.audio-hal-2-0}" ]; then
      IS_HIDL=true
      ui_print "  Audio HAL: HIDL"
fi

# If neither is detected, check for AIDL directly
if [ "$IS_AIDL" = false ] && [ "$IS_HIDL" = false ]; then
    if [ -f "/vendor/bin/hw/android.hardware.audio.service" ] || \
    [ -f "/vendor/bin/hw/android.hardware.audio.service.aidl" ]; then
        IS_AIDL=true
        ui_print "  Audio HAL: AIDL (binary detected)"
    else
        ui_print "  Audio HAL: Unknown, applying safe props only"

# -- Audio Effect app detection --
ui_print""
ui_print "  Detecting audio effect apps..."

HAS_JAMESDSP=false
HAS_V4A=false

# JamesDSP Package names
for PKG in "james.dsp" "me.timschneeberger.rootlessjamesdsp" "james.dsp.manager"; do
    if pm list packages 2>/dev/null | grep -q "$PKG"; then
        HAS_JAMESDSP=true
        ui_print "  ✓ JamesDSP detected ($PKG)"
        break
    fi
done

# V4A Package Names
for PKG in "com.pittvandewitt.viperfx" "com.vipercn.viper4android_v2" "com.vipercn.viper4android"; do
    if pm list packages 2>/dev/null | grep -q "$PKG"; then
        HAS_V4A=true
        ui_print "  ✓ ViPER4Android detected ($PKG)"
        break
    fi
done

if [ "$HAS_JAMESDSP" = false ] && [ "$HAS_V4A" = false ]; then
    ui_print "  No audio effect apps detected"
fi

# -- Universal audio quality props --
ui_print ""
ui_print "  Applying audio quality props..."

# resampler quality
write_prop "af.resampler.quality" "8"

# Audio offload - allows compressed audio bypass of the system mixer
write_prop "audio.offload.disable" "false"
write_prop "audio.offload.min.duration.secs" "15"
write_prop "audio.offload.gapless.ennabled" "true"

# Deep buffer for sustained playback quality
write_prop "audio.deep_buffer.media" "true"

# HIDL-specific props
if [ "$IS_HIDL" = true ]; then
    ui_print "  Applying HIDL-Specific props..."
    write_prop "persist.audio.hifi" "true"
    write_prop "persist.audio.fluence.voicecall" "none"
    write_prop "persist.audio.fluence.speaker" "none"
fi

# -- JamesDSP Optimizations --
if [ "$HAS_JAMESDSP" = true ]; then
    ui_print "  Applying JamesDSP optimizations..."
    # Ensure effects are processed at full quality
    write_prop "audio.effects.skiptranscode" "true"
    # Disable SRC before effects chain where possible
    write_prop "af.fast_track_multiplier" "1"
fi

# -- V4A Optimizations --
if [ "$HAS_V4A" = true ]; then
    ui_print "  Applying ViPER4Android optimizations..."
    write_prop "audio.effects.skiptranscode" "true"
    write_prop "af.fast_track_multilier" "1"
fi

ui_print "  Root manager: $ROOT_MGR"
ui_print ""

ui_print "  Overlay installed..."
ui_print "  Patching audio props..."
ui_print "  Disabling CSD enforcement..."
ui_print "  Clearing safe volume state..."
ui_print ""
ui_print "  ✓ Done! Reboot to apply!"
ui_print ""
ui_print "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
ui_print ""
ui_print "  If this module helped you,"
ui_print "  consider sponsoring us on GitHub!"
ui_print ""
ui_print "  github.com/sponsors/LyrinoxTechnologies"
ui_print ""
ui_print "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
ui_print ""
